### ISSUE TITLE
rcov failing with stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by ghost** [relevance/rcov#1]
This failure was with my test/unit task:

```
namespace :test do
  namespace :rcov do
    desc "generate a coverage report for unit and functional tests together in coverage; see coverage/index.html afterwards"
    task :unit_functional do
      sh "#{RCOV} --rails -n #{EXCLUDE} #{find_source(&rsquo;test/functional&rsquo;)} #{find_source(&rsquo;test/unit&rsquo;)}"
    end
  end
end
```

find_source method just return the _test.rb file names inside the dir.

```
Loaded suite /usr/bin/rcov
Started
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Finished in 150.920127 seconds.

708 tests, 36577 assertions, 0 failures, 0 errors
/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:131:in `wrap': stack level too deep (SystemStackError)
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:131:in `wrap&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:90:in `write_text&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/default.rb:50:in `write&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `each&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in `write&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
 ... 12 levels...
from /usr/lib/ruby/gems/1.8/gems/mergulhao-rcov-0.8.1.3.0/lib/rcov.rb:640:in `each&rsquo;
from /usr/lib/ruby/gems/1.8/gems/mergulhao-rcov-0.8.1.3.0/lib/rcov.rb:640:in `dump_coverage_info&rsquo;
from /usr/lib/ruby/gems/1.8/gems/mergulhao-rcov-0.8.1.3.0/bin/rcov:408
from /usr/lib/ruby/1.8/test/unit.rb:278
rake aborted!
```

It also fails when I run "rake spec:rcov"(now we are moving to rspec):

```
mergulhao@homelinux:~/Desenvolvimento/redeparede$ rake spec:rcov
(in /home/mergulhao/Desenvolvimento/redeparede)
/home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/integration/tasks
rm -r coverage
.....................*........*...........................................

Pending:

MeeboController getfriends should return error when user doesn&rsquo;t exists (Not Yet Implemented)
/home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/rspec-rails/lib/spec/rails/example/controller_example_group.rb:121:in `initialize&rsquo;

MeeboController getinfo should return error when user doesn&rsquo;t exists (Not Yet Implemented)
/home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/rspec-rails/lib/spec/rails/example/controller_example_group.rb:121:in `initialize&rsquo;

Finished in 12.167461 seconds

74 examples, 0 failures, 2 pending
/usr/lib/ruby/1.8/rexml/formatters/pretty.rb:131:in `wrap&rsquo;: stack level too deep (SystemStackError)
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:131:in `wrap&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:90:in `write_text&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/default.rb:50:in `write&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `each&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:73:in `write_element&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/default.rb:31:in `write&rsquo;
from /usr/lib/ruby/1.8/rexml/formatters/pretty.rb:75:in `write_element&rsquo;
 ... 12 levels...
from /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov.rb:640:in `each&rsquo;
from /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.2.1/lib/rcov.rb:640:in `dump_coverage_info&rsquo;
from /usr/lib/ruby/gems/1.8/gems/spicycode-rcov-0.8.2.1/bin/rcov:408
from /home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/rspec/lib/spec/runner.rb:44
rake aborted!
Command /usr/bin/ruby1.8 -I"/home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/rspec/lib" -S rcov --exclude "spec/*,gems/*" --rails -o "coverage" "/home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/rspec/bin/spec" -- "spec/helpers/meebo_helper_spec.rb" "spec/controllers/meebo_controller_spec.rb" "spec/controllers/posts_controller_spec.rb" "spec/controllers/tweets_controller_spec.rb" "spec/models/tweet_spec.rb" "spec/models/lib/rede_twitter_spec.rb" "spec/models/lib/post_finder_spec.rb" "spec/models/post_spec.rb" "spec/models/city_spec.rb" "spec/models/coverage_spec.rb" --options "/home/mergulhao/Desenvolvimento/redeparede/spec/spec.opts" failed

(See full trace by running task with --trace)
```

It started yesterday, but nothing was changed on my local. I thought it can be related to amount of code, but It not much:

```
mergulhao@homelinux:~/Desenvolvimento/redeparede$ rake stats
(in /home/mergulhao/Desenvolvimento/redeparede)
/home/mergulhao/Desenvolvimento/redeparede/vendor/plugins/integration/tasks
+----------------------+-------+-------+---------+---------+-----+-------+
| Name                 | Lines |   LOC | Classes | Methods | M/C | LOC/M |
+----------------------+-------+-------+---------+---------+-----+-------+
| Controllers          |  4190 |  3325 |      56 |     321 |   5 |     8 |
| Helpers              |  1804 |  1535 |       0 |     146 |   0 |     8 |
| Models               |  3808 |  2880 |      60 |     459 |   7 |     4 |
| Libraries            |  2321 |  1687 |      33 |     205 |   6 |     6 |
| Model specs          |   224 |   187 |       0 |       2 |   0 |    91 |
| View specs           |     0 |     0 |       0 |       0 |   0 |     0 |
| Controller specs     |   344 |   274 |       0 |       2 |   0 |   135 |
| Helper specs         |    11 |     7 |       0 |       0 |   0 |     0 |
+----------------------+-------+-------+---------+---------+-----+-------+
| Total                | 12702 |  9895 |     149 |    1135 |   7 |     6 |
+----------------------+-------+-------+---------+---------+-----+-------+
  Code LOC: 9427     Test LOC: 468     Code to Test Ratio: 1:0.0

mergulhao@homelinux:~/Desenvolvimento/redeparede$ 
```

I already worked on rails projects with double than this and worked fine(about 1 year ago).

PS: seens to be related to https://rspec.lighthouseapp.com/projects/5645/tickets/513-rake-spec-rcov-exception

Any idea? Thanks.

[original LH ticket](http://relevance.lighthouseapp.com/projects/16869/tickets/13)

 This ticket has 0 attachment(s).

**Comment by ghost** [comment]
**rcov failing with stack level too deep (SystemStackError)**

Anyone can help on this issue. I still not found a fix.

 by Sylvestre Mergulhão

**Comment by ghost** [comment]
**rcov failing with stack level too deep (SystemStackError)**

spicycode-rcov seems to solve this issue, install as

 @@@ bash
gem install spicycode-rcov -s http://gems.github.com
 @@@

 by Jorge Calás

**Comment by ghost** [comment]
**rcov failing with stack level too deep (SystemStackError)**

Yup, thats the version I&rsquo;m using...

I just reinstalled now and stills with the same error. My version is spicycode-rcov (0.8.2.1).

Thanks.

 by Sylvestre Mergulhão

**Comment by ghost** [comment]
**rcov failing with stack level too deep (SystemStackError)**

As a workaround you could disable all reports except text.  It seems like the final fix would be to make the &rsquo;wrap&rsquo; method in rexml_extensions non-recursive; then it could better use the heap.  As an alternate workaround you could try ulimit -s to increase your stack size.

 by Tom Macklin

**Comment by ghost** [comment]
**rcov failing with stack level too deep (SystemStackError)**

Hey Guys, 

We are actually pulling out all of the REXML code and switching to ERB templates to fix this and a few other issues.

 by Chad Humphries

**Comment by ghost** [comment]
**rcov failing with stack level too deep (SystemStackError)**

Thanks for the replies. When you have some news let me know so I can help you test the new stuff.

 by Sylvestre Mergulhão

**Comment by abedra** [comment]
Sylvestre,

The formatters have been mostly rewritten / replaced.  Please give things another shot and see if you have any more problems

**Comment by ghost** [comment]
closing the issue due to inactivity
