### ISSUE TITLE
Rcov fails in Ruby 1.9.1 with --no-rcovrt flag

### ISSUE THREAD

**Issue by spicycode** [relevance/rcov#24]
The code asplode! :)

```
/Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:160:in `+': nil can't be coerced into Fixnum (TypeError)
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:160:in `block (2 levels) in aggregate_data'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:160:in `each'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:160:in `each_with_index'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:160:in `block in aggregate_data'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:158:in `each_pair'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:158:in `aggregate_data'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/differential_analyzer.rb:112:in `raw_data_relative'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/differential_analyzer.rb:52:in `remove_hook'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/lib/rcov/code_coverage_analyzer.rb:124:in `remove_hook'
    from /Users/chad/.gem/ruby/1.9.1/gems/relevance-rcov-0.8.6/bin/rcov:419:in `block in <top (required)>'
rake aborted!
```

**Comment by natikgadzhi** [comment]
Still fails for me. 
Is there any possible fix?

**Comment by dguettler** [comment]
This is only a quick fix, but it seems to be working fine for me. I updated the function in question to:

```
def aggregate_data(aggregated_data, delta)
  delta.each_pair do |file, cov_arr|
    dest = (aggregated_data[file] ||= Array.new(cov_arr.size, 0))
    cov_arr.each_with_index{|x,i| dest[i] += x.to_i}
  end
end
```

notice the ".to_i" at line 160

**Comment by ghost** [comment]
I will get this fixed this week.  I think I know what's actually going on here.  Thanks for your help!

**Comment by natikgadzhi** [comment]
Thank you, guys. 
I will try the temporary solution tomorrow.

**Comment by ghost** [comment]
This has been pushed in version 0.9.3.  It will be available soon.
